version: '2'
services:
  monitor-docker-slack:
    container_name: monitor-docker-slack
#    image: denny/monitor-docker-slack:latest
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file:
      - .env
    restart: always
